### ISSUE TITLE
Custom method resolver

### ISSUE THREAD

**Issue by maxgorovenko** [yoanm/symfony-jsonrpc-http-server#63]
Tag 'json_rpc_http_server.method_resolver' doesn't work at all. I've searched this string in project and find service with this name, but no tag and its usage.

I try to make my method resolver service with this name and it works.

It looks like a mistake in doc.

php 7.4
symfony 5.1
yoanm/symfony-jsonrpc-http-server 3.0.1

**Comment by maxgorovenko** [comment]
May be I need something else but this. I have to check some http headers to make decision about access rights. Are there some other ways to inject middleware?

**Comment by yoanm** [comment]
Hello,

Yes, after checks it seems to be a mistake when I updated Readme file, this should have been removed. On the last version, method resolver is a simple service locator with a mapping "JSON-RPC method name" => "service id".

I'm not sure to understand what you want to achieve exactly :/ 
You want to check some headers in order to know which method to call or what you want is just a "security" check inside a method to validate that this method can be used ? 
In case it's the second point, you do not need anything more, you can do it inside the PHP method itself. 

If you want something more global (like something which will check if the project itself can be called by someone/something, regardless of the JSON-RPC method), I would use symfony event triggered when an http request is received, use the request stack to retrieve the request and check the header. So something above this JSON-RPC framework.

Currently framework does not allow middleware injection, but you can listen some events triggered (see there the list https://github.com/yoanm/php-jsonrpc-server-sdk#events-dispatched).

Let me know if it's not what you want (in that case, maybe provide some examples, or better the code itself if it's public).

**Comment by maxgorovenko** [comment]
Thanks for your reply. I think symfony event triggered when an http request is received is ok for me.

**Comment by yoanmLf** [comment]
👌 You're welcome

**Comment by yoanm** [comment]
👌 You're welcome
